### ISSUE TITLE
Xcode 8. Swift 3.0

### ISSUE THREAD

**Issue by arcanysjuank** [PureMVC/puremvc-swift-multicore-framework#4]
Hi PureMVC team,

I tried running the app in Xcode 8 (swift 3.0) and seems there are alot of error in the code. Is there a new update for swift 3.0?

Thanks,
John

**Comment by cliffhall** [comment]
Hi John,

In case Saad didn't get back to you directly, I just wanted to report he's been swamped for the last few months but says he is planning to get it back up to speed soon. It would be good if you payed this as an issue on github so you'll get a notification when the changes happen. 

Also, and this is more directed to Saad, I'm not sure if it's just an XCode setup thing or what, but I'd really rather that we didn't need to include the Xcode project at all, particularly since XCode doesn't have a monopoly on being able to work with Swift. Instead, instructions for setup should be added to a markdown file linked to from the README, if it's complicated enough to need one. IMO, this will remove a turbulent dependency (Xcode) and if the port follows the PureMVC maxim of using the simplest possible language features, it should remain stable, since backward incompatible language changes, as a rule, tend to be related to more advanced features.

Cheers,
-=Cliff>

**Comment by cliffhall** [comment]
John,

Just merged Swift 3.0 support. Enjoy!

Cheers,
-=Cliff>
